run_clustering_config_path: "spd/clustering/configs/test-resid_mlp1.json"
n_runs: 2
distances_method: "perm_invariant_hamming"
base_output_dir: "tests/.temp/clustering"
slurm_job_name_prefix: "spd"
slurm_partition: "h100-reserved"
wandb_project: "spd-cluster"
wandb_entity: "goodfire"
create_git_snapshot: false