#!/bin/bash
#SBATCH --job-name=attrib-graphs
#SBATCH --array=0-{n_tasks_minus_one}
#SBATCH --partition={partition}
#SBATCH --gres=gpu:1
#SBATCH --mem={mem}
#SBATCH --cpus-per-task={cpus}
#SBATCH --time={time}
#SBATCH --output={job_dir}/arrays/task_%a/slurm_%j.out
#SBATCH --error={job_dir}/arrays/task_%a/slurm_%j.err

# Attribution Graph Generation - SLURM Array Job
# Generated by slurm.submit_batch

echo "=== SLURM Job Info ==="
echo "Job ID: $SLURM_JOB_ID"
echo "Array Task ID: $SLURM_ARRAY_TASK_ID"
echo "Node: $SLURMD_NODENAME"
echo "GPUs: $CUDA_VISIBLE_DEVICES"
echo "Start time: $(date)"
echo "Working directory: $(pwd)"
echo "====================="

# Change to repository directory
cd {repo_dir}

# Activate virtual environment
if [ -f ".venv/bin/activate" ]; then
    source .venv/bin/activate
fi

# Show Python info
echo "Python: $(which python)"
echo "Python version: $(python --version)"

# Run the worker
echo "Starting worker for task $SLURM_ARRAY_TASK_ID..."
.venv/bin/python -m slurm.worker \
    --job-dir {job_dir} \
    --task-id $SLURM_ARRAY_TASK_ID

EXIT_CODE=$?

echo "=== Job Complete ==="
echo "Exit code: $EXIT_CODE"
echo "End time: $(date)"

exit $EXIT_CODE
