run_config_path: "spd/clustering/configs/example.yaml"
n_runs: 10
base_output_dir: "/mnt/polished-lake/spd/clustering/"
slurm_job_name_prefix: "spd"
slurm_partition: "h100-reserved"
wandb_project: "spd-cluster"
wandb_entity: "goodfire"
create_git_snapshot: true