"""The per-site representation must reproduce the stacked implementation exactly.

Fixtures (`stacked_fixtures.npz`) were generated by `gen_stacked_fixtures.py` running
against the pre-restructure `feature/jax-single-pool-pd` code (stacked `DecompVU`,
contiguous-MLP-only `llama_decomposed_lm`). This test rebuilds the identical model in
the per-site representation and checks, for the same MLP-family site set:

  * clean output / per-site INPUTS (requested by target-owned canonical activation keys) /
    `weight_deltas` / `masked_output` — to a portable fp32 reassociation tolerance (SPEC D4),
    not bit-exact: float32 matmul reduction order differs across CPU microarchitectures, so
    the same op sequence diverges by ~1 ULP between the fixture-generating host and a given
    CI runner (`ubuntu-latest` is a heterogeneous pool). These pins are CI-fn-INDEPENDENT —
    pure target-model forwards — so they still hold against the committed fixtures.

The saved 2-step training-trajectory records (`ci_leaf::*`, `out::step*`,
`out::final_{V,U,src}` in the npz) are no longer tested: they were recorded with the
removed L_p loss, and the old branch that produces this file cannot express the
smooth-L0 loss, so matching records can never be produced again. The forward-pass
comparisons above are what this suite still checks.
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import pytest

from param_decomp.core.components import ComponentStacks, component_stacks_from_sites
from param_decomp.core.model import site_weight_delta
from param_decomp.target_ports.llama import llama3_inv_freq
from param_decomp.targets.glu_transformer import (
    FrozenAttn,
    GatedMLP,
    GLUDecomposedModel,
    GLULayer,
    build_decomposed_lm,
    glu_site_specs,
    mlp_family_site_cs,
    parse_site_name,
)
from param_decomp.targets.testing import (
    capture_clean,
    materialized_logits,
    run_clean,
    run_masked,
    tiny_glu_cfg,
)
from param_decomp.targets.transformer_taps import (
    attention_input_tap_key,
    attention_output_tap_key,
    mlp_hidden_tap_key,
    mlp_input_tap_key,
)

FIXTURES = Path(__file__).resolve().parent / "stacked_fixtures.npz"
RTOL = 1e-4
ATOL = 1e-5

_PENDING_REGEN = pytest.mark.xfail(
    reason=(
        "pending embed-internal golden regen: fixtures are residual-fed but the model "
        "now takes token ids. Regenerate the torch reference + fixtures against the token "
        "contract (torch-oracle worktree)."
    ),
    strict=False,
)


def _load() -> tuple[dict[str, np.ndarray], GLUDecomposedModel, ComponentStacks, jnp.ndarray]:
    assert FIXTURES.exists(), "regenerate via gen_stacked_fixtures.py on the base branch"
    f = dict(np.load(FIXTURES))
    cfg = tiny_glu_cfg()
    first = int(f["_scalar_FIRST_LAYER"])
    last = int(f["_scalar_LAST_LAYER"])
    C = int(f["_scalar_C"])

    def a(key: str) -> jnp.ndarray:
        return jnp.asarray(f[key])

    layers = [
        GLULayer(
            ln1=a(f"tgt::layers.{i}.ln1"),
            ln2=a(f"tgt::layers.{i}.ln2"),
            attn=FrozenAttn(
                a(f"tgt::layers.{i}.wq"),
                a(f"tgt::layers.{i}.wk"),
                a(f"tgt::layers.{i}.wv"),
                a(f"tgt::layers.{i}.wo"),
                cfg.n_head,
                cfg.n_kv_head,
                cfg.head_dim,
                cfg.n_rep,
                "auto",
            ),  # fmt: skip
            mlp=GatedMLP(
                Wg=a(f"tgt::layers.{i}.Wg"),
                Wu=a(f"tgt::layers.{i}.Wu"),
                Wd=a(f"tgt::layers.{i}.Wd"),
            ),
        )
        for i in range(first, cfg.n_layer)
    ]
    sites = glu_site_specs(cfg, mlp_family_site_cs(first, last, C))
    model = build_decomposed_lm(
        embed=jnp.zeros((cfg.vocab_size, cfg.n_embd), jnp.float32),
        layers=layers,
        norm=a("tgt::norm"),
        lm_head=a("tgt::lm_head"),
        inv_freq=llama3_inv_freq(cfg),
        cfg=cfg,
        sites=sites,
    )
    vu = component_stacks_from_sites(
        {s.name: (a(f"vu::V::{s.name}"), a(f"vu::U::{s.name}")) for s in sites}
    )
    return f, model, vu, a("resid")


def _assert_close(got: jnp.ndarray, want: np.ndarray, what: str) -> None:
    np.testing.assert_allclose(np.asarray(got), want, rtol=RTOL, atol=ATOL, err_msg=what)


@_PENDING_REGEN
def test_clean_output_matches():
    f, model, _vu, resid = _load()
    clean = materialized_logits(run_clean(model, resid))
    _assert_close(clean, f["out::clean"], "clean logits")


@_PENDING_REGEN
def test_site_inputs_and_weight_deltas_match():
    f, model, vu, resid = _load()

    def site_input_key(site: str) -> str:
        layer, kind = parse_site_name(site)
        match kind:
            case "q" | "k" | "v":
                return attention_input_tap_key(layer)
            case "o":
                return attention_output_tap_key(layer)
            case "gate" | "up":
                return mlp_input_tap_key(layer)
            case "down":
                return mlp_hidden_tap_key(layer)
            case _:
                raise AssertionError(kind)

    input_keys = tuple(site_input_key(site) for site in model.site_names)
    captures = capture_clean(model, resid, tuple(dict.fromkeys(input_keys)))
    for name, input_key in zip(model.site_names, input_keys, strict=True):
        _assert_close(captures[input_key], f[f"out::site_input::{name}"], f"site_input {name}")
    deltas = model.weight_deltas(vu)
    for name in model.site_names:
        _assert_close(
            site_weight_delta(deltas, vu, name), f[f"out::wd::{name}"], f"weight_delta {name}"
        )


@_PENDING_REGEN
def test_masked_output_match():
    f, model, vu, resid = _load()
    masks = {s: jnp.asarray(f[f"mask::{s}"]) for s in model.site_names}
    delta_masks = {s: jnp.asarray(f[f"delta_mask::{s}"]) for s in model.site_names}
    prepared_weights = model.prepare_compute_weights(vu, None)
    masked_all = materialized_logits(
        run_masked(
            model,
            prepared_weights,
            resid,
            masks,
            delta_masks,
            None,
            True,
            remat=False,
        )
    )
    _assert_close(masked_all, f["out::masked_all"], "masked_output (all live)")
