run_name: pile_llama_simple_mlp-4L-768-untied-sinks
seed: 45
dp: 8
dtype: bfloat16
global_batch: 1024
num_iterations: 100000
warmup_iters: 600
learning_rate: 3e-4
learning_rate_decay_frac: 0.1
weight_decay: 0.1
grad_clip: 1.0
log_every: 100
val_every: 1000
val_steps: 20
save_every: 1000

model:
  model_type: LlamaSimpleMLP
  tie_word_embeddings: false
  attention_sinks: true
  block_size: 512
  vocab_size: 50277
  n_layer: 4
  n_head: 6
  n_embd: 768
  n_intermediate: 3072
  rotary_base: 10000
  n_ctx: 512
  n_key_value_heads: 6
  rms_norm_eps: 1.0e-06

data:
  kind: name
  name: pile_neox_tok_512

wandb:
  project: spd
