name: Build Docker Image

on:
  push:
    branches:
      - feature/mpi-image # TODO: This is just temporarily here so I can test it
  workflow_dispatch: # Must manually trigger this workflow in order to build the image

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .github
          file: .github/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-mpi:latest
